;;; fixtures.el --- Test fixtures for shortcut.el -*- lexical-binding: t; -*-

;; Copyright (C) 2024

;; This file is not part of GNU Emacs.

;;; Commentary:

;; Test fixtures and mock data for shortcut.el tests

;;; Code:

(defvar shortcut-test-story-fixture
  '((id . 12345)
    (name . "Test Story")
    (description . "This is a test story")
    (story_type . "feature")
    (workflow_state_id . 500000001)
    (workflow_id . 500000000)
    (created_at . "2024-01-01T10:00:00Z")
    (updated_at . "2024-01-01T12:00:00Z")
    (completed . :json-false)
    (archived . :json-false)
    (started . t)
    (started_at . "2024-01-01T11:00:00Z")
    (completed_at . nil)
    (app_url . "https://app.shortcut.com/org/story/12345")
    (entity_type . "story")
    (owner_ids . ["uuid-member-123"])
    (follower_ids . ["uuid-member-456" "uuid-member-789"])
    (requested_by_id . "uuid-member-123")
    (epic_id . 67890)
    (iteration_id . nil)
    (estimate . 3)
    (position . 1000)
    (blocked . :json-false)
    (blocker . :json-false)
    (external_links . [])
    (labels . [])
    (tasks . [])
    (comments . [])
    (files . [])
    (linked_files . [])
    (branches . [])
    (commits . [])
    (pull_requests . []))
  "A sample story object matching the Shortcut API specification.")

(defvar shortcut-test-member-fixture
  '((id . "uuid-member-123")
    (entity_type . "member")
    (role . "member")
    (disabled . :json-false)
    (state . "full")
    (created_at . "2023-01-15T08:00:00Z")
    (updated_at . "2024-01-01T10:00:00Z")
    (created_without_invite . :json-false)
    (group_ids . ["uuid-group-1" "uuid-group-2"])
    (profile . ((id . "uuid-profile-123")
                (entity_type . "profile")
                (name . "Test User")
                (mention_name . "testuser")
                (email_address . "test.user@example.com")
                (deactivated . :json-false)
                (is_owner . :json-false)
                (is_agent . :json-false)
                (two_factor_auth_activated . t)
                (gravatar_hash . "abc123")
                (display_icon . ((url . "https://example.com/avatar.png"))))))
  "A sample member object matching the Shortcut API specification.")

(defvar shortcut-test-member-fixture-2
  '((id . "uuid-member-456")
    (entity_type . "member")
    (role . "member")
    (disabled . :json-false)
    (state . "full")
    (created_at . "2023-02-20T09:00:00Z")
    (updated_at . "2024-01-05T14:00:00Z")
    (created_without_invite . :json-false)
    (group_ids . ["uuid-group-1"])
    (profile . ((id . "uuid-profile-456")
                (entity_type . "profile")
                (name . "Follower User 1")
                (mention_name . "follower1")
                (email_address . "follower1@example.com")
                (deactivated . :json-false)
                (is_owner . :json-false)
                (is_agent . :json-false)
                (two_factor_auth_activated . t)
                (gravatar_hash . "def456")
                (display_icon . ((url . "https://example.com/avatar2.png"))))))
  "A second sample member object for testing multiple members.")

(defvar shortcut-test-member-fixture-3
  '((id . "uuid-member-789")
    (entity_type . "member")
    (role . "member")
    (disabled . :json-false)
    (state . "full")
    (created_at . "2023-03-10T10:30:00Z")
    (updated_at . "2024-01-10T16:00:00Z")
    (created_without_invite . :json-false)
    (group_ids . ["uuid-group-2"])
    (profile . ((id . "uuid-profile-789")
                (entity_type . "profile")
                (name . "Follower User 2")
                (mention_name . "follower2")
                (email_address . "follower2@example.com")
                (deactivated . :json-false)
                (is_owner . :json-false)
                (is_agent . :json-false)
                (two_factor_auth_activated . :json-false)
                (gravatar_hash . "ghi789")
                (display_icon . ((url . "https://example.com/avatar3.png"))))))
  "A third sample member object for testing multiple members.")

(defvar shortcut-test-epic-fixture
  '((id . 67890)
    (entity_type . "epic")
    (name . "Test Epic")
    (description . "This is a test epic")
    (state . "in progress")
    (created_at . "2024-01-01T09:00:00Z")
    (updated_at . "2024-01-15T14:00:00Z")
    (archived . :json-false)
    (started . t)
    (started_at . "2024-01-02T10:00:00Z")
    (completed . :json-false)
    (completed_at . nil)
    (completed_at_override . nil)
    (started_at_override . nil)
    (app_url . "https://app.shortcut.com/org/epic/67890")
    (owner_ids . ["uuid-member-123"])
    (follower_ids . ["uuid-member-456"])
    (requested_by_id . "uuid-member-123")
    (epic_state_id . 500000010)
    (labels . [])
    (label_ids . [])
    (comments . [])
    (project_ids . [])
    (group_ids . [])
    (group_id . nil)
    (associated_groups . [])
    (objective_ids . [])
    (mention_ids . [])
    (member_mention_ids . [])
    (group_mention_ids . [])
    (stories_without_projects . 0)
    (position . 1000)
    (global_id . "epic-67890")
    (external_id . nil)
    (milestone_id . nil)
    (planned_start_date . nil)
    (deadline . nil)
    (productboard_plugin_id . nil)
    (productboard_id . nil)
    (productboard_name . nil)
    (productboard_url . nil)
    (stats . ((num_points . 10)
              (num_points_done . 5)
              (num_points_started . 3)
              (num_points_unstarted . 2)
              (num_stories . 5)
              (num_stories_done . 2)
              (num_stories_started . 2)
              (num_stories_unstarted . 1)))
    (health . ((entity_type . "health")
               (id . "uuid-health-123")
               (status . "On Track")
               (text . "All tasks on schedule")
               (author_id . "uuid-author-1")
               (epic_id . 67890)
               (created_at . "2024-01-15T12:00:00Z")
               (updated_at . "2024-01-15T14:00:00Z"))))
  "A sample epic object matching the Shortcut API specification.")

(defvar shortcut-test-workflow-fixture
  '((id . 500000000)
    (entity_type . "workflow")
    (name . "Default Workflow")
    (description . "The default workflow for the team")
    (created_at . "2023-01-01T08:00:00Z")
    (updated_at . "2024-01-01T10:00:00Z")
    (auto_assign_owner . :json-false)
    (project_ids . [])
    (team_id . "uuid-team-123")
    (default_state_id . 500000001)
    (states . [((id . 500000001)
                (entity_type . "workflow-state")
                (name . "Unstarted")
                (type . "unstarted")
                (description . "Work that has not started")
                (color . "#e0e0e0")
                (position . 0)
                (created_at . "2023-01-01T08:00:00Z")
                (updated_at . "2023-01-01T08:00:00Z")
                (num_stories . 10)
                (num_story_templates . 0))
               ((id . 500000002)
                (entity_type . "workflow-state")
                (name . "In Progress")
                (type . "started")
                (description . "Work that is currently in progress")
                (color . "#42a5f5")
                (position . 1)
                (created_at . "2023-01-01T08:00:00Z")
                (updated_at . "2023-01-01T08:00:00Z")
                (num_stories . 5)
                (num_story_templates . 0))
               ((id . 500000003)
                (entity_type . "workflow-state")
                (name . "Done")
                (type . "done")
                (description . "Completed work")
                (color . "#4caf50")
                (position . 2)
                (created_at . "2023-01-01T08:00:00Z")
                (updated_at . "2023-01-01T08:00:00Z")
                (num_stories . 20)
                (num_story_templates . 0))]))
  "A sample workflow object matching the Shortcut API specification.")

(provide 'fixtures)
;;; fixtures.el ends here
